### ISSUE TITLE
Create a simple web page that lists available schemes

### ISSUE THREAD

**Issue by alexbooker** [base16-builder/base16-builder#33] opened 2016-02-07 02:34 UTC
Something like [this](http://chriskempson.github.io/base16/) but dynamically generated based on the [schemes](https://github.com/alexbooker/base16-builder/tree/master/db/schemes) directory.

Ideally this will be hosted on [GitHub pages](https://pages.github.com/) for easy integration and free hosting.

**Comment by aloisdg** [comment] 2016-02-09 18:10
You can check the template called _preview_.

**Comment by alexbooker** [comment] 2016-02-24 09:04
I'm adding this to the `1.0.0-beta` milestone because I think it is essential to give the user a way to explore schemes.

**Comment by aloisdg** [comment] 2016-02-24 09:24
@alexbooker I agree. :+1:

**Comment by alexbooker** [comment] 2016-02-24 09:29
@aloisdg Someone, @cruor99, had the :bulb: idea to make a seperate repository: `base16-builder-gui` - I think that would be _really_ cool. Ideally, it'll use [Electron](http://electron.atom.io/).

I think what I'm going to do for `1.0.0-beta` is distribute an auto-generated `index.html` file with a table of colour palettes. I wanted to do it in the terminal but it isn't really possible as far as I can see.

**Comment by aloisdg** [comment] 2016-02-24 09:55
@alexbooker A GUI would a really nice tool to have. I would love to merge it with a theme editor/generator. But, I think we should move this to a new issue and we should focus on the cli tool. A GUI is an external tool who can be made by someone else or ourself later.

**Comment by alexbooker** [comment] 2016-02-24 11:07
@aloisdg My thoughts exactly.

**Comment by alexbooker** [comment] 2016-02-27 22:48
Done :smile: 

Update Base16 Builder:

     npm install -g base16-builder

And then run 

    base16-builder preview

To preview schemes.


At the moment the UI isn't so nice. @Evinon had a pretty neat concept for a new UI:

![@](http://abload.de/img/desktophd2x6ys95.png)

**Comment by alexbooker** [comment] 2016-02-27 23:04
Todo:

- Rename command to `ls-schemes`
- Write a console message saying "Check your browser"
- Document the feature

**Comment by alexbooker** [comment] 2016-02-27 23:05
Also todo:

- Add `ls-templates` command that writes to the console

**Comment by aloisdg** [comment] 2016-02-28 07:28
Shouldn't be possible to open the browser directly?

**Comment by aloisdg** [comment] 2016-02-28 07:36
Their is a duplicate of the color "09" in the html file.

I like @evinon's concept. Also, a display of the code (like highlight.js) would be a nice add.

**Comment by alexbooker** [comment] 2016-02-28 10:33
> Shouldn't be possible to open the browser directly? (default behavior right now with firefox on windows10)

Can you elaborate? My intention was for the page to open in the default browser.

> I like @evinon's concept. Also, a display of the code (like highlight.js) would be a nice add.

Agree :+1:

**Comment by aloisdg** [comment] 2016-02-28 10:49
> Can you elaborate? My intention was for the page to open in the default browser.

Yes and it is great!

**Comment by alexbooker** [comment] 2016-02-28 11:00
@aloisdg I think something is getting lost in translation.

You said:

> Shouldn't be possible to open the browser directly? 

I don't understand what you mean. Could you please explain in more detail so I can understand?

**Comment by aloisdg** [comment] 2016-02-28 11:10
> I don't understand what you mean.

Me neither. What you did works for me. The page open in my browser.

**Closed** 2016-03-02 21:07 UTC

**Comment by CrashyBang** [comment] 2016-04-18 06:51
Hey Guys,

So I was thinking what if `ls schemes` was to compile all the schemes for Codemirror and then load up a index in the browser with 2 Codemirror editors side by side one light one dark (maybe a snippet selector so you can try a bit of ruby, python, js, etc...) and a scheme picker so you can demo them all there and then and chose one for your editor.

I would be happy to attempt implementing this if you approve.

Pretty much like the old base16-generator preview site:

![image](https://cloud.githubusercontent.com/assets/2978850/14595847/7f851148-0596-11e6-83a5-ee25f69f11c7.png)

**Comment by aloisdg** [comment] 2016-04-18 11:51
@CrashyBang Good idea!

**Comment by alexbooker** [comment] 2016-04-18 13:12
Hey @CrashyBang :smile: 

That sounds awesome. I really like the idea of using CodeMirror. I would love it if you worked on this and will be happy to help where I can.

I would reccomend working iteratively. For example, I think an attainable goal is to make the editor read-only with some pre-defined Ruby code or something. We can add multiple languages etc. in the future.

**Comment by CrashyBang** [comment] 2016-04-18 21:03
Hey @alexbooker,

That's a really good idea, I will get on to that this week, I am have a few questions about conventions / structure but from what I have seen the code base looks rock solid so I should have no trouble :)

**Comment by alexbooker** [comment] 2016-04-19 08:16
Awesome :smile: 

Feel free to shoot me or @aloisdg any questions.

You can message me on [Twitter](https://twitter.com/bookercodes) or add me on Hangouts (alexbooker@fastmail.im).

Oh, and I created [a new issue](https://github.com/base16-builder/base16-builder/issues/96) to keep track of all this. Please continue the conversation there!
