### ISSUE TITLE
Won't work on Node v 6.0 because of broken dependency

### ISSUE THREAD

**Issue by nakamin** [base16-builder/base16-builder#105] opened 2016-05-06 18:06 UTC
Quite a long chain here so bear with me:
B16B has [unicode](https://www.npmjs.com/package/unicode) as a dependency, which has [bufferstream](https://www.npmjs.com/package/bufferstream) as a dependency which has [bufferjs](https://www.npmjs.com/package/bufferjs) as a dependancy which hasn't been updated in forever and won't work on Node v 6.0
See this issue for the error message that I'm getting: https://github.com/coolaj86/node-bufferjs/issues/13

**Comment by alexbooker** [comment] 2016-05-06 18:17
Hi :wave: 

I think the `unicode` dependency must come from [`slug`](https://github.com/base16-builder/base16-builder/blob/master/package.json#L52).  `slug` hasn't been updated in quite some time but there's [`fork`](https://github.com/Zertz/mollusc) that seems to be on top of this.

**Comment by nakamin** [comment] 2016-05-06 18:19
Probably but downgrading Node fixed this for me. So I guess just put a warning in the readme for now...

**Comment by alexbooker** [comment] 2016-05-06 18:21
Any reason why we shouldn't just use the fork?

And **thank you** for taking the time to investigate this in the first place :smile:

**Comment by nakamin** [comment] 2016-05-06 18:25
No I don't see any reason, just time, how long will this take to implement? Would be good to test it too before deploy
No problem btw this tool is awesome, and I love your videos too especially the most recent one on &Vote, great stuff!

**Comment by alexbooker** [comment] 2016-05-06 18:29
Thank you :smile:!

Hm... :confused: I tried to reproduce the error but I cannot:

![](http://i.imgur.com/9BbLVc4.png)

Any ideas?

**Comment by nakamin** [comment] 2016-05-06 18:37
You already have it installed though

**Comment by nakamin** [comment] 2016-05-06 18:37
I couldn't install it and I'm also on Windows

**Comment by alexbooker** [comment] 2016-05-06 19:38
I re-installed it before running the test.

I'll check on Windows next.

**Comment by nakamin** [comment] 2016-05-06 19:42
OK btw I forgot to mention, I have the logs. I'll upload when I get back home.

**Comment by alexbooker** [comment] 2016-05-06 19:52
I managed to reproduce the error on Windows 10.

**Comment by nakamin** [comment] 2016-05-06 19:54
Good because that means I'm not wasting your time. Bad because it's broken
:sad:

**Comment by alexbooker** [comment] 2016-05-06 20:22
I made a pull request https://github.com/coolaj86/node-bufferjs/pull/14

I _think_ if @coolaj86 merges it and keeps the [major version number (`2`)](https://github.com/dodo/node-bufferstream/blob/master/package.json#L14) this will be fixed

**Comment by nakamin** [comment] 2016-05-06 20:31
If I'm not mistaken coolaj86/node-bufferjs#12 already fixes this but good job anyway. Why did they even use get?

**Closed** 2016-05-06 20:47 UTC

**Comment by alexbooker** [comment] 2016-05-06 21:00
This should be fixed now :smile: 

Thanks

**Comment by nakamin** [comment] 2016-05-06 21:01
Yep good solution lol :smile:
